require: rubocop-performance
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - bin/**
    - spec/**/*
    - db/schema.rb

Lint/AssignmentInCondition:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
