inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - bin/**
    - db/schema.rb
    - node_modules/**/*

Lint/AssignmentInCondition:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false
