require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-graphql
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - bin/**
    - spec/**/*
    - db/schema.rb

# Layout
Layout/HashAlignment:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

# Lint
Lint/AssignmentInCondition:
  Enabled: false

# Style
Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

# Metrics
Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

# GraphQL
GraphQL/FieldDescription:
  Enabled: false

GraphQL/ArgumentDescription:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

GraphQL/ExtractInputType:
  Enabled: false

GraphQL/ExtractType:
  Enabled: false

GraphQL/OrderedFields:
  Enabled: false

GraphQL/OrderedArguments:
  Enabled: false
