language: ruby
cache: bundler
sudo: false
rvm:
  - 2.6.3
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rubocop
  - bundle exec rspec
deploy:
  provider: heroku
  app:
    master: auspices-atlas-production
  api_key:
    secure: isA6G+pW7WqTI1oj+Rkdjbp3wig27a2Na3PoCfsMJQgSd5xTzo9yrwXLBQfGVJV1p2IV2TA9bxp5Ilu/QtMW1hPxQ+zWxyOnPY5+DtyfJNCXnPZYf+Cc1HktbUgLxcihvAhxvPPCeQJWxUezf3+YIAGkQbJem8De2R8MtgFBXj8=
