language: ruby
cache: bundler
rvm:
- 2.2.0
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
script:
- bundle exec rubocop
- bundle exec rspec
deploy:
  provider: heroku
  app:
    master: auspices-atlas-production
  api_key:
    secure: oiKeWk6WH3M3km3y3VB5IdfC+6z4vGoitlPrqWuEvv3IVWfW+SiACuU6dCQZn53TGD3BVAIflG/kd4EL2UfrCtRSSiv+A3ZTsHQijb2fWoPHvH4CD/lqEo7U7vndjL69u7satQt4gO4Vw46TqM6RJvPpCjRc3KII3OMiZw+sHA8=
