defaults: &defaults
  adapter: postgresql
  encoding: unicode
  variables:
    statement_timeout: 5000

development:
  <<: *defaults
  database: db/atlas_development
  host: /tmp

test:
  <<: *defaults
  database: db/atlas_test
  host: /tmp
