defaults: &defaults
  adapter: postgresql
  encoding: unicode

development:
  <<: *defaults
  database: db/atlas_development
  host: /tmp

test:
  <<: *defaults
  database: db/atlas_test
  host: /tmp
